name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Check Node.js version
        run: node --version

      - name: Install dependencies
        run: npm install

      - name: Check Cypress version
        run: npx cypress --version

      - name: Check Node.js and npm versions
        run: |
          node --version
          npm --version

      - name: Run Cypress tests with debug
        run: DEBUG=cypress:* npx cypress run
